name = "MyExample2"
uuid = "d32ac25a-548e-41fe-b556-0a255125d648"
authors = ["m-arifin"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
